name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
      confirmation:
        description: 'Type "destroy" to confirm deletion of all resources'
        required: true

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

permissions:
  id-token: write
  contents: read

jobs:

  destroy-ecs:
    runs-on: ubuntu-latest
    env:
      TF_VAR_frontend_image_uri: ${{ needs.deploy-ecr.outputs.frontend_ecr_repo }}:${{ github.sha }}
      TF_VAR_backend_image_uri: ${{ needs.deploy-ecr.outputs.backend_ecr_repo }}:${{ github.sha }}
      TF_VAR_db_endpoint: ${{ secrets.DB_ENDPOINT }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Check confirmation
        if: github.event.inputs.confirmation != 'destroy'
        run: |
          echo "Error: Confirmation word 'destroy' not provided or incorrect. Aborting destruction."
          echo "Please ensure you type 'destroy' in the confirmation input."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Destroy ECS Infrastructure
        working-directory: terraform/compute/ecs
        run: |
          terraform init
          terraform destroy -auto-approve

  destroy-ecr:
    needs: destroy-ecs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Destroy ECR Infrastructure
        working-directory: terraform/compute/ecr
        run: |
          terraform init
          terraform destroy -auto-approve

  destroy-database:
    needs: destroy-ecr
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Destroy Database Infrastructure
        working-directory: terraform/database
        run: |
          terraform init
          terraform destroy -auto-approve

  destroy-network:
    needs: destroy-database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Destroy Network Infrastructure
        working-directory: terraform/network
        run: |
          terraform init
          terraform destroy -auto-approve 